export const API_CONFIG = {
  BASE_URL: 'https://jayyogeshwar.com/milk_dist_system/customer/customer.php',
  deleteCustomer: 'https://jayyogeshwar.com/milk_dist_system/customer/customer.php',
  deleteSeller: 'https://jayyogeshwar.com/milk_dist_system/seller/seller.php',
  featch: 'https://jayyogeshwar.com/milk_dist_system/customer/customer.php/?path=customers',
  addSellerApi: 'https://jayyogeshwar.com/milk_dist_system/seller/seller.php',
  milkApi: 'https://jayyogeshwar.com/milk_dist_system/admin/milk_assignment.php',
  milkApi2: 'https://jayyogeshwar.com/milk_dist_system/seller/seller.php',
  trackMilkApi: 'https://jayyogeshwar.com/milk_dist_system/seller/track_customer_detail.php',
  sellermilkdistrubiute: 'https://jayyogeshwar.com/milk_dist_system/seller/seller_give_milk_to_customer.php',
  featch_customer_data_for_thair_app: 'https://jayyogeshwar.com/milk_dist_system/customer/featch_customer_data_for_thair_app.php',
  login: 'https://jayyogeshwar.com/milk_dist_system/login/login.php',
  fetchSeller: 'https://jayyogeshwar.com/milk_dist_system/seller/seller.php',
  addAddress: 'https://jayyogeshwar.com/milk_dist_system/admin/address.php',
  getAddressSelect: 'https://jayyogeshwar.com/milk_dist_system/seller/getSelectAddress.php',
  getDistributeMilkData: 'https://jayyogeshwar.com/milk_dist_system/admin/getDistributeMilkData.php',
  gatherPaymentSeller: 'https://jayyogeshwar.com/milk_dist_system/seller/gether_payment.php',
  get_payment: 'https://jayyogeshwar.com/milk_dist_system/admin/payment_get.php',
  seller_detail_page: 'https://jayyogeshwar.com/milk_dist_system/admin/seller_detail_page.php',
  admin_deashbord: 'https://jayyogeshwar.com/milk_dist_system/admin/admin_deashbord.php',
  seller_deashbord: 'https://jayyogeshwar.com/milk_dist_system/seller/seller_dashboard.php', 
  get_seller: "https://jayyogeshwar.com/milk_dist_system/admin/get_seller.php"
};
// export const API_CONFIG = {
//   BASE_URL: 'http://192.168.101.171/milk_dist_system/customer/customer.php',
//   deleteCustomer: 'http://192.168.101.171/milk_dist_system/customer/customer.php',
//   deleteSeller: 'https://192.168.101.171/milk_dist_system/seller/seller.php',
//   featch: 'http://192.168.101.171/milk_dist_system/customer/customer.php/?path=customers',
//   addSellerApi: 'http://192.168.101.171/milk_dist_system/seller/seller.php',
//   milkApi: 'http://192.168.101.171/milk_dist_system/admin/milk_assignment.php',
//   milkApi2: 'http://192.168.101.171/milk_dist_system/seller/seller.php',
//   trackMilkApi: 'http://192.168.101.171/milk_dist_system/seller/track_customer_detail.php',
//   sellermilkdistrubiute: 'http://192.168.101.171/milk_dist_system/seller/seller_give_milk_to_customer.php',
//   featch_customer_data_for_thair_app: 'http://192.168.101.171/milk_dist_system/customer/featch_customer_data_for_thair_app.php',
//   login: 'http://192.168.101.171/milk_dist_system/login/login.php',
//   fetchSeller: 'http://192.168.101.171/milk_dist_system/seller/seller.php',
//   addAddress: 'http://192.168.101.171/milk_dist_system/admin/address.php',
//   getAddressSelect: 'http://192.168.101.171/milk_dist_system/seller/getSelectAddress.php',
//   getDistributeMilkData: 'http://192.168.101.171/milk_dist_system/admin/getDistributeMilkData.php',
//   gatherPaymentSeller: 'http://192.168.101.171/milk_dist_system/seller/gether_payment.php',
//   get_payment: 'http://192.168.101.171/milk_dist_system/admin/payment_get.php',
//   seller_detail_page: 'http://192.168.101.171/milk_dist_system/admin/seller_detail_page.php',
//   admin_deashbord: 'http://192.168.101.171/milk_dist_system/admin/admin_deashbord.php',
//   seller_deashbord: 'http://192.168.101.171/milk_dist_system/seller/seller_dashboard.php',
//   get_seller:  "http://192.168.101.171/milk_dist_system/admin/get_seller.php"
// };
